project:
  type: website
  output-dir: docs
  execute-dir: project

website:
  title: "Generalized Linear Hierarchical models in brms"
  navbar:
    tools:
      - icon: github
        href: https://github.com/bios2/hiermod

format:
  html:
    theme: solar
    css: styles.css
    toc: true

editor: source

execute: 
  freeze: true

